kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "hibernate"
spec:
  source:
    git:
      uri: "https://github.com/AdlerFleurant/hibernate-orm.git"
      ref: "jenkins"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile.groovy
      env:
      - name: XMX
        value: 7g
    type: JenkinsPipeline